from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CALCULATOR(object):
    def setupUi(self, CALCULATOR):
        CALCULATOR.setObjectName("CALCULATOR")
        CALCULATOR.resize(629, 343)
        CALCULATOR.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        CALCULATOR.setMouseTracking(True)
        self.gridLayout = QtWidgets.QGridLayout(CALCULATOR)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_12 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 1, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 4, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 4, 3, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 5, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 5, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 5, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(CALCULATOR)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 5, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(CALCULATOR)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 4)

        self.retranslateUi(CALCULATOR)
        QtCore.QMetaObject.connectSlotsByName(CALCULATOR)

    def retranslateUi(self, CALCULATOR):
        _translate = QtCore.QCoreApplication.translate
        CALCULATOR.setWindowTitle(_translate("CALCULATOR", "CALCULATOR"))
        self.pushButton_12.setText(_translate("CALCULATOR", "AC"))
        self.pushButton_18.setText(_translate("CALCULATOR", "√"))
        self.pushButton_19.setText(_translate("CALCULATOR", "%"))
        self.pushButton_13.setText(_translate("CALCULATOR", "/"))
        self.pushButton_4.setText(_translate("CALCULATOR", "7"))
        self.pushButton_11.setText(_translate("CALCULATOR", "8"))
        self.pushButton_8.setText(_translate("CALCULATOR", "9"))
        self.pushButton_16.setText(_translate("CALCULATOR", "x"))
        self.pushButton_2.setText(_translate("CALCULATOR", "4"))
        self.pushButton_5.setText(_translate("CALCULATOR", "5"))
        self.pushButton_6.setText(_translate("CALCULATOR", "6"))
        self.pushButton_14.setText(_translate("CALCULATOR", "-"))
        self.pushButton.setText(_translate("CALCULATOR", "1"))
        self.pushButton_3.setText(_translate("CALCULATOR", "2"))
        self.pushButton_9.setText(_translate("CALCULATOR", "3"))
        self.pushButton_15.setText(_translate("CALCULATOR", "+"))
        self.pushButton_21.setText(_translate("CALCULATOR", "π"))
        self.pushButton_10.setText(_translate("CALCULATOR", "0"))
        self.pushButton_17.setText(_translate("CALCULATOR", "."))
        self.pushButton_7.setText(_translate("CALCULATOR", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CALCULATOR = QtWidgets.QWidget()
    ui = Ui_CALCULATOR()
    ui.setupUi(CALCULATOR)
    CALCULATOR.show()
    sys.exit(app.exec_())
